"""Reviewed statewide learning context; never a deposit or backyard forecast.

Material names are selected facts from USGS state-industry overviews. They can
include mined commodities rather than readily identifiable surface specimens.
NPS fossil categories are learning examples, not current designation claims.
"""
from core.us_places import STATE_NAMES

FOSSIL_SOURCE = "https://www.nps.gov/subjects/fossils/official-state-fossils.htm"
SURVEY_DIRECTORY = "https://www.stategeologists.org/surveys"
STATES = {'AK': {'fossil_example': 'Ice Age mammoths',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'gemstones',
                      'gold',
                      'silver',
                      'zinc',
                      'lead'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-alaska',
        'reviewed': '2026-10-07',
        'survey': None},
 'AL': {'fossil_example': 'Ancient whales',
        'materials': ['sand and gravel', 'crushed stone', 'bentonite', 'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-alabama',
        'reviewed': '2026-10-07',
        'survey': {'name': 'Geological Survey of Alabama', 'url': 'https://gsa.state.al.us/'}},
 'AR': {'fossil_example': '',
        'materials': ['tripoli', 'bromine compounds', 'kaolin', 'silica'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-arkansas',
        'reviewed': '2026-10-07',
        'survey': None},
 'AZ': {'fossil_example': 'Petrified wood',
        'materials': ['dimension stone',
                      'clay',
                      'gypsum',
                      'bentonite',
                      'salt',
                      'silver',
                      'copper',
                      'zeolites'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-arizona',
        'reviewed': '2026-10-07',
        'survey': {'name': 'Arizona Geological Survey', 'url': 'https://azgs.arizona.edu/'}},
 'CA': {'fossil_example': 'Sabertooth cats',
        'materials': ['feldspar', 'diatomite', 'pumice', 'boron', 'rare earths'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-california',
        'reviewed': '2026-10-07',
        'survey': {'name': 'California Geological Survey',
                   'url': 'https://www.conservation.ca.gov/CGS/'}},
 'CO': {'fossil_example': 'Plated dinosaurs',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'clay',
                      'gypsum',
                      'bentonite',
                      'gold',
                      'silver'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-colorado',
        'reviewed': '2026-10-07',
        'survey': None},
 'CT': {'fossil_example': 'Dinosaur tracks',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'limestone',
                      'granite',
                      'sandstone'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-connecticut',
        'reviewed': '2026-10-07',
        'survey': None},
 'DC': {'fossil_example': 'Theropod dinosaurs',
        'materials': [],
        'mineral_source': '',
        'reviewed': '2026-10-07',
        'survey': None},
 'DE': {'fossil_example': 'Belemnites',
        'materials': ['sand and gravel', 'magnesium compounds'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-delaware',
        'reviewed': '2026-10-07',
        'survey': None},
 'FL': {'fossil_example': 'Fossil coral',
        'materials': ['staurolite', 'attapulgite', 'phosphate rock'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-florida',
        'reviewed': '2026-10-07',
        'survey': {'name': 'Geological Survey of Florida', 'url': 'https://floridadep.gov/fgs'}},
 'GA': {'fossil_example': 'Shark teeth',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'feldspar',
                      'gemstones',
                      'kaolin',
                      'mica'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-georgia',
        'reviewed': '2026-10-07',
        'survey': None},
 'HI': {'fossil_example': '',
        'materials': ['peridot', 'obsidian', 'sand and gravel', 'crushed stone', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-hawaii',
        'reviewed': '2026-10-07',
        'survey': None},
 'IA': {'fossil_example': '',
        'materials': ['geodes',
                      'barite',
                      'sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'gypsum',
                      'limestone',
                      'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-iowa',
        'reviewed': '2026-10-07',
        'survey': None},
 'ID': {'fossil_example': 'Ancient horses',
        'materials': ['dimension stone',
                      'pumice',
                      'feldspar',
                      'gemstones',
                      'silver',
                      'copper',
                      'zinc',
                      'lead'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-idaho',
        'reviewed': '2026-10-07',
        'survey': {'name': 'Idaho Geological Survey', 'url': 'https://idahogeology.org/'}},
 'IL': {'fossil_example': 'Tully Monster',
        'materials': ['clay', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-illinois',
        'reviewed': '2026-10-07',
        'survey': None},
 'IN': {'fossil_example': 'Mastodons',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'gypsum',
                      'limestone',
                      'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-indiana',
        'reviewed': '2026-10-07',
        'survey': None},
 'KS': {'fossil_example': 'Marine reptiles',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'gypsum',
                      'pumice',
                      'gemstones',
                      'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-kansas',
        'reviewed': '2026-10-07',
        'survey': None},
 'KY': {'fossil_example': 'Brachiopods',
        'materials': ['crushed stone', 'clay', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-kentucky',
        'reviewed': '2026-10-07',
        'survey': None},
 'LA': {'fossil_example': 'Petrified palm wood',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'clay',
                      'gypsum',
                      'sandstone',
                      'gemstones',
                      'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-louisiana',
        'reviewed': '2026-10-07',
        'survey': None},
 'MA': {'fossil_example': 'Dinosaur tracks',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'granite',
                      'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-massachusetts',
        'reviewed': '2026-10-07',
        'survey': None},
 'MD': {'fossil_example': 'Fossil snails',
        'materials': ['sand and gravel', 'crushed stone', 'dimension stone', 'clay', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-maryland',
        'reviewed': '2026-10-07',
        'survey': None},
 'ME': {'fossil_example': 'Fossil plants',
        'materials': ['dimension stone', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-maine',
        'reviewed': '2026-10-07',
        'survey': None},
 'MI': {'fossil_example': 'Fossil coral',
        'materials': ['sand and gravel',
                      'dimension stone',
                      'clay',
                      'gypsum',
                      'gemstones',
                      'potash',
                      'salt',
                      'iron ore'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-michigan',
        'reviewed': '2026-10-07',
        'survey': None},
 'MN': {'fossil_example': '',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'gemstones',
                      'iron ore'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-minnesota',
        'reviewed': '2026-10-07',
        'survey': None},
 'MO': {'fossil_example': 'Crinoids',
        'materials': ['crushed stone',
                      'dimension stone',
                      'clay',
                      'gemstones',
                      'silver',
                      'copper',
                      'zinc',
                      'lead'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-missouri',
        'reviewed': '2026-10-07',
        'survey': None},
 'MS': {'fossil_example': 'Ancient whales',
        'materials': ['sand and gravel', 'crushed stone', 'clay', 'bentonite'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-mississippi',
        'reviewed': '2026-10-07',
        'survey': None},
 'MT': {'fossil_example': 'Duckbilled dinosaurs',
        'materials': ['dimension stone',
                      'gemstones',
                      'bentonite',
                      'talc',
                      'gold',
                      'silver',
                      'copper'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-montana',
        'reviewed': '2026-10-07',
        'survey': None},
 'NC': {'fossil_example': 'Shark teeth',
        'materials': ['crushed stone', 'clay', 'granite', 'feldspar', 'mica', 'phosphate rock'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-north-carolina',
        'reviewed': '2026-10-07',
        'survey': None},
 'ND': {'fossil_example': 'Petrified wood',
        'materials': ['sand and gravel', 'crushed stone', 'clay', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-north-dakota',
        'reviewed': '2026-10-07',
        'survey': {'name': 'North Dakota Geological Survey',
                   'url': 'https://www.dmr.nd.gov/ndgs/'}},
 'NE': {'fossil_example': 'Ice Age mammoths',
        'materials': ['sand and gravel', 'crushed stone', 'clay'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-nebraska',
        'reviewed': '2026-10-07',
        'survey': None},
 'NH': {'fossil_example': '',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'granite',
                      'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-new-hampshire',
        'reviewed': '2026-10-07',
        'survey': None},
 'NJ': {'fossil_example': 'Duckbilled dinosaurs',
        'materials': ['sand and gravel', 'crushed stone'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-new-jersey',
        'reviewed': '2026-10-07',
        'survey': {'name': 'New Jersey Geological and Water Survey',
                   'url': 'https://dep.nj.gov/njgws/'}},
 'NM': {'fossil_example': 'Theropod dinosaurs',
        'materials': ['dimension stone',
                      'clay',
                      'gypsum',
                      'pumice',
                      'gemstones',
                      'potash',
                      'salt',
                      'gold'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-new-mexico',
        'reviewed': '2026-10-07',
        'survey': None},
 'NV': {'fossil_example': 'Ichthyosaurs',
        'materials': ['magnesite',
                      'barite',
                      'dimension stone',
                      'gypsum',
                      'diatomite',
                      'gemstones',
                      'bentonite',
                      'kaolin'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-nevada',
        'reviewed': '2026-10-07',
        'survey': None},
 'NY': {'fossil_example': 'Sea scorpions',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'gemstones',
                      'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-new-york',
        'reviewed': '2026-10-07',
        'survey': None},
 'OH': {'fossil_example': 'Trilobites',
        'materials': ['crushed stone',
                      'dimension stone',
                      'limestone',
                      'sandstone',
                      'gemstones',
                      'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-ohio',
        'reviewed': '2026-10-07',
        'survey': None},
 'OK': {'fossil_example': 'Theropod dinosaurs',
        'materials': ['crushed stone', 'gypsum', 'limestone', 'pumice', 'feldspar', 'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-oklahoma',
        'reviewed': '2026-10-07',
        'survey': None},
 'OR': {'fossil_example': 'Conifer leaves',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'clay',
                      'diatomite',
                      'gemstones',
                      'bentonite',
                      'salt',
                      'zeolites'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-oregon',
        'reviewed': '2026-10-07',
        'survey': None},
 'PA': {'fossil_example': 'Trilobites',
        'materials': ['sand and gravel', 'crushed stone'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-pennsylvania',
        'reviewed': '2026-10-07',
        'survey': {'name': 'Pennsylvania Geological Survey',
                   'url': 'https://www.dcnr.pa.gov/Geology/Pages/default.aspx'}},
 'PR': {'fossil_example': '',
        'materials': ['sand and gravel', 'crushed stone', 'salt'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-puerto-rico',
        'reviewed': '2026-10-07',
        'survey': None},
 'RI': {'fossil_example': '',
        'materials': ['sand and gravel', 'crushed stone'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-rhode-island',
        'reviewed': '2026-10-07',
        'survey': None},
 'SC': {'fossil_example': 'Ice Age mammoths',
        'materials': ['crushed stone', 'kaolin', 'vermiculite', 'gold'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-south-carolina',
        'reviewed': '2026-10-07',
        'survey': None},
 'SD': {'fossil_example': 'Horned dinosaurs',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'gypsum',
                      'feldspar',
                      'gemstones',
                      'mica',
                      'gold'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-south-dakota',
        'reviewed': '2026-10-07',
        'survey': {'name': 'South Dakota Geological Survey', 'url': 'https://www.sdgs.usd.edu/'}},
 'TN': {'fossil_example': 'Bivalve shells',
        'materials': ['dimension stone', 'clay', 'marble', 'sandstone', 'gemstones', 'zinc'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-tennessee',
        'reviewed': '2026-10-07',
        'survey': None},
 'TX': {'fossil_example': 'Petrified palm wood',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'gypsum',
                      'bentonite',
                      'zeolites'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-texas',
        'reviewed': '2026-10-07',
        'survey': None},
 'UT': {'fossil_example': 'Theropod dinosaurs',
        'materials': ['beryllium',
                      'clay',
                      'bentonite',
                      'potash',
                      'gold',
                      'silver',
                      'copper',
                      'iron ore'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-utah',
        'reviewed': '2026-10-07',
        'survey': None},
 'VA': {'fossil_example': 'Bivalve shells',
        'materials': ['dimension stone',
                      'clay',
                      'limestone',
                      'granite',
                      'feldspar',
                      'mica',
                      'vermiculite'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-virginia',
        'reviewed': '2026-10-07',
        'survey': None},
 'VT': {'fossil_example': 'Beluga whales',
        'materials': ['slate', 'sand and gravel', 'crushed stone', 'granite', 'talc'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-vermont',
        'reviewed': '2026-10-07',
        'survey': None},
 'WA': {'fossil_example': 'Ice Age mammoths',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'diatomite',
                      'gold'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-washington',
        'reviewed': '2026-10-07',
        'survey': None},
 'WI': {'fossil_example': 'Trilobites',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'limestone',
                      'dolomite',
                      'dimension stone',
                      'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-wisconsin',
        'reviewed': '2026-10-07',
        'survey': None},
 'WV': {'fossil_example': 'Ground sloths',
        'materials': ['sand and gravel', 'crushed stone', 'dimension stone', 'clay', 'gemstones'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-west-virginia',
        'reviewed': '2026-10-07',
        'survey': None},
 'WY': {'fossil_example': 'Fossil fish',
        'materials': ['sand and gravel',
                      'crushed stone',
                      'dimension stone',
                      'clay',
                      'gypsum',
                      'limestone',
                      'bentonite'],
        'mineral_source': 'https://www.usgs.gov/centers/national-minerals-information-center/mineral-industry-wyoming',
        'reviewed': '2026-10-07',
        'survey': None}}


def state_context(state):
    if not isinstance(state, str) or state not in STATES:
        return ""
    record = STATES[state]
    lines = [f"### {STATE_NAMES[state]} starting points", "",
             "Statewide background, not evidence of a find in your yard.", ""]
    if record['materials']:
        materials = ', '.join(record['materials'])
        lines += [f"**Mineral materials to learn about:** {materials}. "
                  f"[USGS state overview]({record['mineral_source']}) lists these in statewide industry context; "
                  "production does not establish a local deposit or collectible specimen.", ""]
    if record['fossil_example']:
        lines += [f"**Fossil learning example:** {record['fossil_example']}. "
                  f"[NPS state fossil learning guide]({FOSSIL_SOURCE}). "
                  "A state example does not identify fossils at your town point.", ""]
    else:
        lines += ["**Fossil learning:** this state's example is not in the reviewed NPS learning list. "
                  "A local formation map or survey can help; missing guide coverage does not mean no fossils.", ""]
    survey = record['survey']
    if survey:
        lines += [f"**Local maps and identification:** [{survey['name']}]({survey['url']}).", ""]
    else:
        lines += [f"**Local maps and identification:** find your state's survey in the "
                  f"[state geological surveys directory]({SURVEY_DIRECTORY}).", ""]
    lines += ["For historical objects, check dated building/land-use records or "
              "[Library of Congress Sanborn maps](https://www.loc.gov/collections/sanborn-maps/about-this-collection/). "
              "Choose a town and Explore for rock-map evidence at its public representative point.", ""]
    return '\n'.join(lines)
