"""Step 5: Embed processed records into Python data files.

Reads existing data files, merges new records, rewrites files maintaining
exact same structure and function signatures.
"""

import logging
import sys
import textwrap
from pathlib import Path

logger = logging.getLogger("scraper")

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "atlas" / "gui" / "data"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def _load_existing_known_sites() -> list[tuple]:
    """Load existing sites as list of (name, lon, lat, period, site_type, state) tuples."""
    from atlas.gui.data.known_sites_expanded import get_known_sites_geojson
    geojson = get_known_sites_geojson()
    sites = []
    for feat in geojson["features"]:
        props = feat["properties"]
        coords = feat["geometry"]["coordinates"]
        sites.append((
            props["name"], coords[0], coords[1],
            props["period"], props["site_type"], props["state"],
        ))
    return sites


def _load_existing_search_index() -> dict:
    """Load existing search index."""
    from atlas.gui.data.search_index import get_search_index
    return dict(get_search_index())


def _format_tuple_str(t: tuple) -> str:
    """Format a tuple for Python source code."""
    parts = []
    for v in t:
        if isinstance(v, str):
            # Escape quotes and backslashes
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            parts.append(f'"{escaped}"')
        elif isinstance(v, float):
            parts.append(f"{v}")
        elif isinstance(v, int):
            parts.append(f"{v}")
        else:
            parts.append(repr(v))
    return f"({', '.join(parts)})"


def embed_known_sites(records: list[dict], dry_run: bool = False) -> int:
    """Embed records into known_sites_expanded.py.

    Returns count of new sites added.
    """
    existing = _load_existing_known_sites()
    existing_set = {(t[0].lower(), round(t[1], 3), round(t[2], 3)) for t in existing}

    new_tuples = []
    for rec in records:
        if "known_sites" not in rec.get("layers", {}):
            continue
        key = (rec["name"].lower(), round(rec["lon"], 3), round(rec["lat"], 3))
        if key in existing_set:
            continue
        existing_set.add(key)
        new_tuples.append((
            rec["name"], rec["lon"], rec["lat"],
            rec.get("period", ""), rec.get("site_type", ""),
            rec.get("state", ""),
        ))

    if not new_tuples:
        logger.info("[embedder] No new known sites to embed")
        return 0

    if dry_run:
        logger.info(f"[embedder] DRY RUN: Would add {len(new_tuples)} sites to known_sites_expanded.py")
        return len(new_tuples)

    # Read existing file to find insertion point
    filepath = DATA_DIR / "known_sites_expanded.py"
    content = filepath.read_text(encoding="utf-8")

    # Find the closing bracket of the sites list
    # We insert new entries just before the final "]" of the sites list
    insert_marker = "    ]\n\n    features = []"

    new_entries = "\n        # =====================================================================\n"
    new_entries += "        # SCRAPED SITES (auto-generated by scrape_databases.py)\n"
    new_entries += "        # =====================================================================\n"
    for t in new_tuples:
        new_entries += f"        {_format_tuple_str(t)},\n"

    content = content.replace(
        insert_marker,
        new_entries + "    ]\n\n    features = []",
    )

    filepath.write_text(content, encoding="utf-8")
    logger.info(f"[embedder] Added {len(new_tuples)} sites to known_sites_expanded.py (total: {len(existing) + len(new_tuples)})")
    return len(new_tuples)


def embed_terrain_anomalies(records: list[dict], dry_run: bool = False) -> int:
    """Embed terrain anomaly records.

    terrain_anomalies.py uses separate lists per anomaly type:
    _MOUND_SITES, _LINEAR_RAISED_SITES, etc.
    Each tuple: (name, lon, lat, description, estimated_period, confidence)
    """
    filepath = DATA_DIR / "terrain_anomalies.py"
    content = filepath.read_text(encoding="utf-8")

    # Group new records by anomaly type
    by_type: dict[str, list[tuple]] = {}
    for rec in records:
        layer_info = rec.get("layers", {}).get("terrain_anomalies")
        if not layer_info:
            continue
        atype = layer_info["anomaly_type"]
        t = (
            rec["name"], rec["lon"], rec["lat"],
            rec.get("description", "")[:200] or rec.get("site_type", ""),
            rec.get("period", "") or "Unknown",
            rec.get("confidence", 0.7),
        )
        by_type.setdefault(atype, []).append(t)

    total_new = sum(len(v) for v in by_type.values())
    if not total_new:
        logger.info("[embedder] No new terrain anomalies to embed")
        return 0

    if dry_run:
        logger.info(f"[embedder] DRY RUN: Would add {total_new} terrain anomalies")
        return total_new

    # Map anomaly types to their list variable names
    type_to_var = {
        "mound": "_MOUND_SITES",
        "linear_raised": "_LINEAR_RAISED_SITES",
        "enclosure": "_ENCLOSURE_SITES",
        "platform_terrace": "_PLATFORM_TERRACE_SITES",
        "depression": "_DEPRESSION_SITES",
        "linear_depression": "_DEPRESSION_SITES",  # Merge with depression
    }

    for atype, tuples in by_type.items():
        var_name = type_to_var.get(atype)
        if not var_name:
            continue

        # Find the closing "]" of this list
        import re
        pattern = re.compile(rf'({re.escape(var_name)}.*?)(^\])', re.MULTILINE | re.DOTALL)
        match = pattern.search(content)
        if not match:
            logger.warning(f"[embedder] Could not find {var_name} in terrain_anomalies.py")
            continue

        new_entries = "    # --- Scraped sites ---\n"
        for t in tuples:
            new_entries += f"    {_format_tuple_str(t)},\n"

        end_pos = match.end(2)
        content = content[:match.start(2)] + new_entries + "]\n" + content[end_pos + 1:]

    filepath.write_text(content, encoding="utf-8")
    logger.info(f"[embedder] Added {total_new} terrain anomalies")
    return total_new


def embed_cave_shelters(records: list[dict], dry_run: bool = False) -> int:
    """Embed cave/shelter records.

    cave_shelters.py tuples: (lon, lat, name, shelter_type_short, description, estimated_period, earliest_date_bp, confidence)
    """
    filepath = DATA_DIR / "cave_shelters.py"
    content = filepath.read_text(encoding="utf-8")

    new_entries = []
    for rec in records:
        layer_info = rec.get("layers", {}).get("cave_shelters")
        if not layer_info:
            continue
        t = (
            rec["lon"], rec["lat"], rec["name"],
            layer_info["shelter_short"],
            rec.get("description", "")[:200] or rec.get("site_type", ""),
            rec.get("period", "") or "Unknown",
            0,  # earliest_date_bp unknown
            rec.get("confidence", 0.7),
        )
        new_entries.append(t)

    if not new_entries:
        return 0

    if dry_run:
        logger.info(f"[embedder] DRY RUN: Would add {len(new_entries)} cave/shelters")
        return len(new_entries)

    # Find the end of the main data list (before the function)
    marker = "\ndef get_cave_shelters_geojson()"
    if marker not in content:
        marker = "\ndef get_cave_shelters_geojson"
    idx = content.find(marker)
    if idx < 0:
        logger.warning("[embedder] Could not find insertion point in cave_shelters.py")
        return 0

    # Find the last "]" before the function definition
    last_bracket = content.rfind("]", 0, idx)
    if last_bracket < 0:
        return 0

    insert_text = "\n    # --- Scraped cave/shelter sites ---\n"
    for t in new_entries:
        insert_text += f"    {_format_tuple_str(t)},\n"

    content = content[:last_bracket] + insert_text + content[last_bracket:]
    filepath.write_text(content, encoding="utf-8")
    logger.info(f"[embedder] Added {len(new_entries)} cave/shelters")
    return len(new_entries)


def embed_soil_anomalies(records: list[dict], dry_run: bool = False) -> int:
    """Embed soil anomaly records.

    soil_anomalies.py tuples: (name, lon, lat, width_deg, height_deg, soil_type, description, confidence)
    """
    filepath = DATA_DIR / "soil_anomalies.py"
    content = filepath.read_text(encoding="utf-8")

    new_entries = []
    for rec in records:
        layer_info = rec.get("layers", {}).get("soil_anomalies")
        if not layer_info:
            continue
        t = (
            rec["name"], rec["lon"], rec["lat"],
            0.005, 0.004,  # Default small extent
            layer_info["soil_type"],
            rec.get("description", "")[:200] or rec.get("site_type", ""),
            rec.get("confidence", 0.7),
        )
        new_entries.append(t)

    if not new_entries:
        return 0

    if dry_run:
        logger.info(f"[embedder] DRY RUN: Would add {len(new_entries)} soil anomalies")
        return len(new_entries)

    # Find insertion point: before get_soil_anomalies_geojson function
    marker = "\ndef get_soil_anomalies_geojson"
    idx = content.find(marker)
    if idx < 0:
        return 0
    last_bracket = content.rfind("]", 0, idx)
    if last_bracket < 0:
        return 0

    insert_text = "\n    # --- Scraped soil anomaly sites ---\n"
    for t in new_entries:
        insert_text += f"    {_format_tuple_str(t)},\n"

    content = content[:last_bracket] + insert_text + content[last_bracket:]
    filepath.write_text(content, encoding="utf-8")
    logger.info(f"[embedder] Added {len(new_entries)} soil anomalies")
    return len(new_entries)


def embed_search_index(records: list[dict], dry_run: bool = False) -> int:
    """Embed records into search_index.py.

    search_index.py is a dict mapping lowercase search terms to
    {"center": [lat, lon], "zoom": int, "label": str}
    """
    existing = _load_existing_search_index()

    new_entries = {}
    for rec in records:
        if "search_index" not in rec.get("layers", {}):
            continue
        name = rec.get("name", "").strip()
        if not name:
            continue

        key = name.lower()
        if key in existing or key in new_entries:
            continue

        state = rec.get("state", "")
        label = f"{name}, {state}" if state else name

        # Zoom level based on site importance
        confidence = rec.get("confidence", 0.5)
        if confidence >= 0.9:
            zoom = 13
        elif confidence >= 0.7:
            zoom = 14
        else:
            zoom = 15

        new_entries[key] = {
            "center": [rec["lat"], rec["lon"]],
            "zoom": zoom,
            "label": label,
        }

    if not new_entries:
        logger.info("[embedder] No new search index entries")
        return 0

    if dry_run:
        logger.info(f"[embedder] DRY RUN: Would add {len(new_entries)} search index entries")
        return len(new_entries)

    filepath = DATA_DIR / "search_index.py"
    content = filepath.read_text(encoding="utf-8")

    # Find the closing "}" of _INDEX dict
    # Insert before the final "}"
    last_brace = content.rfind("}")
    if last_brace < 0:
        return 0

    insert_text = "\n    # --- Scraped search entries ---\n"
    for key, val in sorted(new_entries.items()):
        center_str = f"[{val['center'][0]}, {val['center'][1]}]"
        # Sanitize key and label -- remove quotes that would break Python syntax
        safe_key = key.replace('"', '').replace("'", "")
        safe_label = val['label'].replace('"', "'")
        insert_text += f'    "{safe_key}": {{"center": {center_str}, "zoom": {val["zoom"]}, "label": "{safe_label}"}},\n'

    content = content[:last_brace] + insert_text + content[last_brace:]
    filepath.write_text(content, encoding="utf-8")
    logger.info(f"[embedder] Added {len(new_entries)} search index entries")
    return len(new_entries)


def embed_records(records: list[dict], dry_run: bool = False) -> dict[str, int]:
    """Embed all classified records into their target data files.

    Returns dict mapping layer name to count of records embedded.
    """
    results = {}

    # Load existing sites for dedup reference
    existing_sites = _load_existing_known_sites()
    logger.info(f"[embedder] Existing known sites: {len(existing_sites)}")

    results["known_sites"] = embed_known_sites(records, dry_run)
    results["terrain_anomalies"] = embed_terrain_anomalies(records, dry_run)
    results["cave_shelters"] = embed_cave_shelters(records, dry_run)
    results["soil_anomalies"] = embed_soil_anomalies(records, dry_run)
    results["search_index"] = embed_search_index(records, dry_run)

    total = sum(results.values())
    logger.info(f"[embedder] Total embedded: {total} across {len(results)} layers")
    for layer, count in results.items():
        if count:
            logger.info(f"  {layer}: +{count}")

    return results
