"""Embed deduplicated fossil records into Python data files.

Creates three GeoJSON-returning data files:
  - dinosaur_fossils.py
  - megafauna_fossils.py
  - paleo_plants.py
"""

import json
import logging
import sys
from pathlib import Path

logger = logging.getLogger("scraper")

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "atlas" / "gui" / "data"


def _escape(s: str) -> str:
    """Escape a string for embedding in Python source."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")


def _build_geojson_source(records: list[dict], func_name: str, docstring: str,
                           property_fields: list[str]) -> str:
    """Build Python source code for a GeoJSON data file."""
    lines = [
        '"""Auto-generated fossil data. Do not edit manually.',
        '',
        f'Generated by fossil_embedder.py from scraped paleontological databases.',
        '"""',
        '',
        '',
        f'def {func_name}() -> dict:',
        f'    """{docstring}"""',
        '',
        '    features = [',
    ]

    for rec in records:
        props_parts = []
        for field in property_fields:
            val = rec.get(field)
            if val is None:
                props_parts.append(f'"{field}": None')
            elif isinstance(val, (int, float)):
                props_parts.append(f'"{field}": {val}')
            else:
                props_parts.append(f'"{field}": "{_escape(str(val))}"')

        props_str = ", ".join(props_parts)
        lon = rec["lon"]
        lat = rec["lat"]
        lines.append(
            f'        {{"type": "Feature", "geometry": {{"type": "Point", "coordinates": [{lon}, {lat}]}}, '
            f'"properties": {{{props_str}}}}},'
        )

    lines.append('    ]')
    lines.append('')
    lines.append('    return {')
    lines.append('        "type": "FeatureCollection",')
    lines.append('        "features": features,')
    lines.append('    }')
    lines.append('')

    return "\n".join(lines)


def embed_dinosaur_fossils(records: list[dict], dry_run: bool = False) -> int:
    """Embed dinosaur and marine reptile fossils."""
    # Include dinosaurs, marine reptiles, other vertebrates, and invertebrates
    # The "Dinosaur & Mesozoic Fossil Sites" layer covers all deep-time paleontology
    dino_records = [r for r in records
                    if r.get("taxon_group") in ("dinosaur", "marine_reptile",
                                                 "other_vertebrate", "invertebrate")]

    if not dino_records:
        logger.info("[fossil_embedder] No dinosaur records to embed")
        return 0

    if dry_run:
        logger.info(f"[fossil_embedder] DRY RUN: Would embed {len(dino_records)} dinosaur fossils")
        return len(dino_records)

    source = _build_geojson_source(
        dino_records,
        "get_dinosaur_fossils_geojson",
        "Return GeoJSON FeatureCollection of dinosaur and Mesozoic fossil sites in the US.\\n"
        "\\n"
        "Sources: GBIF, PaleoBioDB, iDigBio, Neotoma.\\n"
        "Each feature is a point representing one or more fossil occurrences at that location.",
        ["name", "common_name", "taxon_group", "time_period", "age_mya",
         "specimen_count", "genus", "family", "order", "institution", "state", "source"],
    )

    filepath = DATA_DIR / "dinosaur_fossils.py"
    filepath.write_text(source, encoding="utf-8")

    size_mb = len(source.encode("utf-8")) / (1024 * 1024)
    logger.info(f"[fossil_embedder] Wrote {len(dino_records)} dinosaur fossils to {filepath} ({size_mb:.1f} MB)")

    if size_mb > 3.0:
        logger.warning(f"[fossil_embedder] dinosaur_fossils.py is {size_mb:.1f} MB (target <3 MB)")

    return len(dino_records)


def embed_megafauna_fossils(records: list[dict], dry_run: bool = False) -> int:
    """Embed Pleistocene megafauna fossils."""
    mega_records = [r for r in records if r.get("taxon_group") == "megafauna"]

    if not mega_records:
        logger.info("[fossil_embedder] No megafauna records to embed")
        return 0

    if dry_run:
        logger.info(f"[fossil_embedder] DRY RUN: Would embed {len(mega_records)} megafauna fossils")
        return len(mega_records)

    # Check proximity to known Paleoindian sites
    paleo_sites = _load_paleoindian_sites()
    if paleo_sites:
        for rec in mega_records:
            rec["near_paleoindian"] = _is_near_paleoindian(
                rec["lat"], rec["lon"], paleo_sites
            )
    else:
        for rec in mega_records:
            rec["near_paleoindian"] = False

    source = _build_geojson_source(
        mega_records,
        "get_megafauna_fossils_geojson",
        "Return GeoJSON FeatureCollection of Pleistocene megafauna fossil sites.\\n"
        "\\n"
        "Includes: mammoths, mastodons, saber-tooth cats, giant ground sloths,\\n"
        "dire wolves, American lions, giant beavers, and other Ice Age megafauna.\\n"
        "\\n"
        "These sites are archaeologically significant because many overlap with\\n"
        "Paleoindian kill sites (Clovis, Folsom, etc.).",
        ["name", "common_name", "genus", "family", "time_period", "age_mya",
         "specimen_count", "near_paleoindian", "institution", "state", "source"],
    )

    filepath = DATA_DIR / "megafauna_fossils.py"
    filepath.write_text(source, encoding="utf-8")

    size_mb = len(source.encode("utf-8")) / (1024 * 1024)
    logger.info(f"[fossil_embedder] Wrote {len(mega_records)} megafauna fossils to {filepath} ({size_mb:.1f} MB)")

    if size_mb > 2.0:
        logger.warning(f"[fossil_embedder] megafauna_fossils.py is {size_mb:.1f} MB (target <2 MB)")

    return len(mega_records)


def embed_paleo_plants(records: list[dict], dry_run: bool = False) -> int:
    """Embed paleobotanical and palynological sites."""
    plant_records = [r for r in records if r.get("taxon_group") == "ancient_plant"]

    if not plant_records:
        logger.info("[fossil_embedder] No plant records to embed")
        return 0

    if dry_run:
        logger.info(f"[fossil_embedder] DRY RUN: Would embed {len(plant_records)} paleo plant sites")
        return len(plant_records)

    # Determine site type from dataset_type or taxonomy
    for rec in plant_records:
        ds = (rec.get("dataset_type") or "").lower()
        if ds == "pollen":
            rec["site_type"] = "pollen_core"
        elif ds == "plant macrofossil":
            rec["site_type"] = "macrofossil"
        elif ds == "charcoal":
            rec["site_type"] = "charcoal"
        elif rec.get("kingdom", "").lower() == "plantae":
            rec["site_type"] = "macrofossil"
        else:
            rec["site_type"] = "paleobotanical"

    source = _build_geojson_source(
        plant_records,
        "get_paleo_plants_geojson",
        "Return GeoJSON FeatureCollection of paleobotanical and palynological sites.\\n"
        "\\n"
        "Includes fossil plants, pollen cores, and charcoal records that document\\n"
        "past environments. Critical for understanding why ancient peoples lived\\n"
        "where they did — forests, grasslands, coastlines all shaped settlement.",
        ["name", "site_type", "time_period", "age_mya", "dataset_type",
         "specimen_count", "genus", "family", "institution", "state", "source"],
    )

    filepath = DATA_DIR / "paleo_plants.py"
    filepath.write_text(source, encoding="utf-8")

    size_mb = len(source.encode("utf-8")) / (1024 * 1024)
    logger.info(f"[fossil_embedder] Wrote {len(plant_records)} paleo plant sites to {filepath} ({size_mb:.1f} MB)")

    if size_mb > 2.0:
        logger.warning(f"[fossil_embedder] paleo_plants.py is {size_mb:.1f} MB (target <2 MB)")

    return len(plant_records)


def _load_paleoindian_sites() -> list[tuple[float, float]]:
    """Load known Paleoindian site locations for proximity matching."""
    try:
        if str(PROJECT_ROOT) not in sys.path:
            sys.path.insert(0, str(PROJECT_ROOT))
        from atlas.gui.data.known_sites_expanded import get_known_sites_geojson
        geojson = get_known_sites_geojson()

        paleo_keywords = {"paleoindian", "clovis", "folsom", "cumberland",
                          "dalton", "hell gap", "gainey", "suwannee",
                          "simpson", "redstone", "eden", "scottsbluff",
                          "mammoth kill", "bison kill", "kill site"}
        sites = []
        for feat in geojson["features"]:
            props = feat["properties"]
            combined = f"{props.get('name', '')} {props.get('period', '')} {props.get('site_type', '')}".lower()
            if any(kw in combined for kw in paleo_keywords):
                coords = feat["geometry"]["coordinates"]
                sites.append((coords[1], coords[0]))  # (lat, lon)

        logger.info(f"[fossil_embedder] Loaded {len(sites)} Paleoindian reference sites")
        return sites
    except Exception as e:
        logger.warning(f"[fossil_embedder] Could not load Paleoindian sites: {e}")
        return []


def _is_near_paleoindian(lat: float, lon: float,
                          paleo_sites: list[tuple[float, float]],
                          threshold_km: float = 10.0) -> bool:
    """Check if a fossil site is within threshold_km of any Paleoindian site."""
    import math
    R = 6371.0
    for plat, plon in paleo_sites:
        dlat = math.radians(lat - plat)
        dlon = math.radians(lon - plon)
        a = (math.sin(dlat / 2) ** 2 +
             math.cos(math.radians(lat)) * math.cos(math.radians(plat)) *
             math.sin(dlon / 2) ** 2)
        dist = R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        if dist <= threshold_km:
            return True
    return False


def embed_fossil_records(records: list[dict], dry_run: bool = False) -> dict[str, int]:
    """Embed all classified fossil records into their data files.

    Returns dict mapping layer name to count of records embedded.
    """
    results = {}
    results["dinosaur_fossils"] = embed_dinosaur_fossils(records, dry_run)
    results["megafauna_fossils"] = embed_megafauna_fossils(records, dry_run)
    results["paleo_plants"] = embed_paleo_plants(records, dry_run)

    total = sum(results.values())
    logger.info(f"[fossil_embedder] Total embedded: {total}")
    return results
